image: node:12
stages:
  - build
  - test
cache:
  key: same-everywhere
  paths:
    - node_modules/
install_dependencies:
  stage: build
  script:
    - cp config.example.js config.js
    - yarn
  artifacts:
    paths:
      - node_modules/
test_lint:
  stage: test
  script: yarn lint
test_unit:
  stage: test
  script: yarn test:unit
