
import React from 'react'
import { castFuzzyBool } from 'utils/misc'
import { compose, path } from 'ramda'
import { Button, Dialog, DialogActions, DialogContent, DialogTitle } from '@material-ui/core'
import ApiClient from 'api-client/ApiClient'

export const hasLoggingEnabled = compose(castFuzzyBool, path(['tags', 'pf9-system:logging']))

const { appbert } = ApiClient.getInstance()

const LoggingAddonDialog = ({ rows: [cluster], onClose }) => {
  const enabled = hasLoggingEnabled(cluster)
  const toggleLogging = () => {
    try {
      appbert.getPackages().then(pkgs => {
        const logPkg = (pkgs || []).filter(pkg => (
          pkg.name === 'pf9-log'
        ))
        if (logPkg === null || logPkg.length === 0) {
          console.log('no logging package found')
          onClose()
          return
        }
        const logId = logPkg[0].ID
        appbert.toggleAddon(cluster.uuid, logId, !enabled).then(() => {
          onClose()
        })
      })
    } catch (e) {
      // TODO: Raise toaster notification
      console.log(e)
    }
  }

  return (
    <Dialog open onClose={onClose}>
      <DialogTitle>Logging Add-On (Beta)</DialogTitle>
      <DialogContent>
        <p>
          <b>Note:</b> Logging is a Beta feature
        </p>
        <p>
          After enabling logging add on, you will be able to forward logs generated by Kubernetes components and user applications
          to log datastores such as ElasticSearch and S3.
        </p>
      </DialogContent>
      <DialogActions>
        <Button color="primary" type="submit" variant="contained" onClick={toggleLogging}>
          {enabled ? 'Disable' : 'Enable'}
        </Button>
        <Button variant="contained" onClick={onClose}>
          Cancel
        </Button>
      </DialogActions>
    </Dialog>
  )
}

export default LoggingAddonDialog
