enum DataKeys {
  Regions = 'Regions',
  Flavors = 'Flavors',
  Nodes = 'Nodes',
  Clusters = 'Clusters',
  Pods = 'Pods',
  ResMgrHosts = 'ResMgrHosts',
  CombinedHosts = 'CombinedHosts',
  CoreApiResources = 'CoreApiResources',
  ApiResources = 'ApiResources',
  Deployments = 'Deployments',
  KubeServices = 'KubeServices',
  Namespaces = 'Namespaces',
  AppDetails = 'AppDetails',
  Apps = 'Apps',
  SupportedRoleVersions = 'SupportedRoleVersions',
  AppVersions = 'AppVersions',
  ApiGroups = 'ApiGroups',
  Releases = 'Releases',
  ReleaseDetail = 'ReleaseDetail',
  RepositoriesWithClusters = 'RepositoriesWithClusters',
  Repositories = 'Repositories',
  CloudProviders = 'CloudProviders',
  CloudProviderDetails = 'CloudProviderDetails',
  CloudProviderRegionDetails = 'CloudProviderRegionDetails',
  ClusterTags = 'ClusterTags',
  ClusterRoles = 'ClusterRoles',
  PrometheusInstances = 'PrometheusInstances',
  ServiceAccounts = 'ServiceAccounts',
  PrometheusRules = 'PrometheusRules',
  PrometheusServiceMonitors = 'PrometheusServiceMonitors',
  PrometheusAlertManagers = 'PrometheusAlertManagers',
  StorageClasses = 'StorageClasses',
  Loggings = 'Loggings',
  Alerts = 'Alerts',
  AlertRules = 'AlertRules',
  AlertsTimeSeries = 'AlertsTimeSeries',
  ApiEndpoints = 'ApiAccess-endpoints',
  Ssh = 'Ssh',
  ServiceCatalog = 'ServiceCatalog',
  Services = 'Services',
  Endpoints = 'Endpoints',
  KubeRoles = 'KubeRoles',
  RoleBindings = 'RoleBindings',
  ClusterRoleBindings = 'ClusterRoleBindings',
  ManagementUsers = 'ManagementUsers',
  ManagementTenants = 'ManagementTenants',
  ManagementRoles = 'ManagementRoles',
  ManagementTenantsRoleAssignments = 'ManagementTenantsRoleAssignments',
  ManagementUsersRoleAssignments = 'ManagementUsersRoleAssignments',
  ManagementGroups = 'ManagementGroups',
  ManagementGroupsMappings = 'ManagementGroupsMappings',
  ManagementCredentials = 'ManagementCredentials',
  Tenants = 'Tenants',
  Users = 'Users',
  UserTenants = 'UserTenants',
}

export default DataKeys

export const ActionDataKeys = {
  Regions: 'Regions',
  Flavors: 'Flavors',
  Nodes: 'Nodes',
  Clusters: 'Clusters',
  Pods: 'Pods',
  ResMgrHosts: 'ResMgrHosts',
  CombinedHosts: 'CombinedHosts',
  CoreApiResources: 'CoreApiResources',
  ApiResources: 'ApiResources',
  Deployments: 'Deployments',
  KubeServices: 'KubeServices',
  Namespaces: 'Namespaces',
  AppDetails: 'AppDetails',
  Apps: 'Apps',
  SupportedRoleVersions: 'SupportedRoleVersions',
  AppVersions: 'AppVersions',
  ApiGroups: 'ApiGroups',
  Releases: 'Releases',
  ReleaseDetail: 'ReleaseDetail',
  RepositoriesWithClusters: 'RepositoriesWithClusters',
  Repositories: 'Repositories',
  CloudProviders: 'CloudProviders',
  CloudProviderDetails: 'CloudProviderDetails',
  CloudProviderRegionDetails: 'CloudProviderRegionDetails',
  ClusterTags: 'ClusterTags',
  ClusterRoles: 'ClusterRoles',
  PrometheusInstances: 'PrometheusInstances',
  ServiceAccounts: 'ServiceAccounts',
  PrometheusRules: 'PrometheusRules',
  PrometheusServiceMonitors: 'PrometheusServiceMonitors',
  PrometheusAlertManagers: 'PrometheusAlertManagers',
  StorageClasses: 'StorageClasses',
  Loggings: 'Loggings',
  Alerts: 'Alerts',
  AlertRules: 'AlertRules',
  AlertsTimeSeries: 'AlertsTimeSeries',
  ApiEndpoints: 'ApiAccess-endpoints',
  Ssh: 'Ssh',
  ServiceCatalog: 'ServiceCatalog',
  Services: 'Services',
  Endpoints: 'Endpoints',
  KubeRoles: 'KubeRoles',
  RoleBindings: 'RoleBindings',
  ClusterRoleBindings: 'ClusterRoleBindings',
  ManagementUsers: 'ManagementUsers',
  ManagementTenants: 'ManagementTenants',
  ManagementRoles: 'ManagementRoles',
  ManagementTenantsRoleAssignments: 'ManagementTenantsRoleAssignments',
  ManagementUsersRoleAssignments: 'ManagementUsersRoleAssignments',
  ManagementGroupsRoleAssignments: 'ManagementGroupsRoleAssignments',
  ManagementGroups: 'ManagementGroups',
  ManagementGroupsMappings: 'ManagementGroupsMappings',
  ManagementCredentials: 'ManagementCredentials',
  Tenants: 'Tenants',
  Users: 'Users',
  UserTenants: 'UserTenants',
}
