// Generated by https://quicktype.io

export interface GetVirtualMachines {
  apiVersion: string
  items: IVirtualMachine[]
  kind: string
  metadata: IVirtualMachineMetadata
}

export interface IVirtualMachine {
  clusterId: string
  apiVersion: string
  kind: string
  metadata: ItemMetadata
  spec: ItemSpec
  status: Status
}

export interface ItemMetadata {
  annotations: Annotations
  creationTimestamp: string
  generation: number
  managedFields: ManagedField[]
  name: string
  namespace: string
  resourceVersion: string
  selfLink: string
  uid: string
}

export interface Annotations {
  'kubevirt.io/latest-observed-api-version': string
  'kubevirt.io/storage-observed-api-version': string
  'kubectl.kubernetes.io/last-applied-configuration'?: string
}

export interface ManagedField {
  apiVersion: string
  fieldsType: string
  fieldsV1: FieldsV1
  manager: string
  operation: string
  time: string
}

export interface FieldsV1 {
  'f:spec'?: FieldsV1FSpec
  'f:metadata'?: FieldsV1FMetadata
  'f:status'?: FStatus
}

export interface FieldsV1FMetadata {
  'f:annotations': FAnnotations
}

export interface FAnnotations {
  '.'?: Empty
  'f:kubevirt.io/latest-observed-api-version'?: Empty
  'f:kubevirt.io/storage-observed-api-version'?: Empty
  'f:kubectl.kubernetes.io/last-applied-configuration'?: Empty
}

// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface Empty {}

export interface FieldsV1FSpec {
  '.'?: Empty
  'f:dataVolumeTemplates'?: Empty
  'f:running'?: Empty
  'f:template'?: FTemplate
}

export interface FTemplate {
  '.': Empty
  'f:metadata'?: FTemplateFMetadata
  'f:spec': FTemplateFSpec
}

export interface FTemplateFMetadata {
  '.': Empty
  'f:labels': FLabels
}

export interface FLabels {
  '.': Empty
  'f:kubevirt.io/size': Empty
}

export interface FTemplateFSpec {
  '.': Empty
  'f:domain': FDomain
  'f:networks': Empty
  'f:volumes': Empty
}

export interface FDomain {
  '.': Empty
  'f:devices': FDevices
  'f:resources': FResources
}

export interface FDevices {
  '.': Empty
  'f:disks': Empty
  'f:interfaces': Empty
}

export interface FResources {
  '.': Empty
  'f:requests': FRequests
}

export interface FRequests {
  '.': Empty
  'f:memory': Empty
}

export interface FStatus {
  '.': Empty
  'f:created': Empty
  'f:volumeSnapshotStatuses': Empty
  'f:conditions'?: Empty
  'f:ready'?: Empty
}

export interface ItemSpec {
  dataVolumeTemplates?: DataVolumeTemplate[]
  running: boolean
  template: Template
}

export interface DataVolumeTemplate {
  metadata: DataVolumeTemplateMetadata
  spec: DataVolumeTemplateSpec
}

export interface DataVolumeTemplateMetadata {
  creationTimestamp: null
  name: string
}

export interface DataVolumeTemplateSpec {
  pvc: Pvc
  source: Source
}

export interface Pvc {
  accessModes: string[]
  resources: PvcResources
}

export interface PvcResources {
  requests: PurpleRequests
}

export interface PurpleRequests {
  storage: string
}

export interface Source {
  http: HTTP
}

export interface HTTP {
  url: string
}

export interface Template {
  metadata: TemplateMetadata
  spec: TemplateSpec
}

export interface TemplateMetadata {
  creationTimestamp: null
  labels?: Labels
}

export interface Labels {
  'kubevirt.io/size': string
}

export interface TemplateSpec {
  domain: Domain
  networks: Network[]
  volumes: Volume[]
}

export interface Domain {
  devices: Devices
  machine: Machine
  resources: DomainResources
}

export interface Devices {
  disks: DiskElement[]
  interfaces: Interface[]
}

export interface DiskElement {
  disk: DiskDisk
  name: string
}

export interface DiskDisk {
  bus: string
}

export interface Interface {
  masquerade?: Empty
  name: string
  sriov?: Empty
}

export interface Machine {
  type: string
}

export interface DomainResources {
  requests: FluffyRequests
}

export interface FluffyRequests {
  memory: string
}

export interface Network {
  name: string
  pod?: Empty
  multus?: Multus
}

export interface Multus {
  networkName: string
}

export interface Volume {
  dataVolume?: DataVolume
  name: string
  cloudInitNoCloud?: CloudInitNoCloud
  containerDisk?: ContainerDisk
}

export interface CloudInitNoCloud {
  userDataBase64: string
}

export interface ContainerDisk {
  image: string
}

export interface DataVolume {
  name: string
}

export interface Status {
  created: boolean
  volumeSnapshotStatuses: VolumeSnapshotStatus[]
  conditions?: Condition[]
  ready?: boolean
}

export interface Condition {
  lastProbeTime: null
  lastTransitionTime: string
  status: string
  type: string
}

export interface VolumeSnapshotStatus {
  enabled: boolean
  name: string
  reason: string
}

export interface IVirtualMachineMetadata {
  continue: string
  resourceVersion: string
  selfLink: string
}
